import Head from 'next/head'
import { RandomFox } from '@/components/RandomFox'
export default function Home() {
  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello worlds</h1>
        <RandomFox />
      </main>
    </>
  )
}
